name: ebisu_dlang
version: 0.0.4
author: Daniel Davidson <dbdavidson@yahoo.com>
homepage: https://github.com/patefacio/ebisu_dlang
description: >
  A library that supports code generation of the D Programming Language
dependencies:
  ebisu: ">=0.0.4"

  logging: ">=0.7.1"

# custom <ebisu_dlang dependencies>

# end <ebisu_dlang dependencies>

dev_dependencies:
  hop: ">=0.27.0"

# custom <ebisu_dlang dev dependencies>
# end <ebisu_dlang dev dependencies>


