name: ebisu_dlang
version: 0.0.1
author: Daniel Davidson <dbdavidson@yahoo.com>
homepage: https://github.com/patefacio/ebisu_dlang
description: >
  A library that supports code generation of dart and others
dependencies:
  ebisu: ">=0.0.2"

  logging: ">=0.7.1"

# custom <ebisu_dlang dependencies>

# end <ebisu_dlang dependencies>

dev_dependencies:
  hop: ">=0.24.4"

# custom <ebisu_dlang dev dependencies>
# end <ebisu_dlang dev dependencies>


